USE casacidada;

CREATE TABLE USUARIO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	CPF VARCHAR(11) UNIQUE,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(60) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL,
	TELEFONE VARCHAR(11),
	DATA_NASC DATE,
	DATA_CRIACAO DATE 
);

CREATE TABLE IMOVEL(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	CEP VARCHAR(20) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    COMPLEMENTO VARCHAR(50),
	NUM_RESIDENCIA INT NOT NULL,
	NOME_PROPRIETARIO VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
    STATUS VARCHAR(10),
    DESCRICAO VARCHAR(100)
);

CREATE TABLE VOLUNTARIO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	AREA_ATUACAO VARCHAR (15),
	DATA_ENTRADA DATE NOT NULL,
	CONSTRAINT FK_ID_USUARIO_VOLUNTARIO FOREIGN KEY (ID) REFERENCES USUARIO (ID)
);

CREATE TABLE GESTOR (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	AREA_ATUACAO VARCHAR (15),
	DATA_ENTRADA DATE NOT NULL,
	CONSTRAINT FK_ID_USUARIO_GESTOR FOREIGN KEY (ID) REFERENCES USUARIO (ID)
);

CREATE TABLE DOADOR (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TIPO VARCHAR(15),
	DATA_ENTRADA DATE NOT NULL,
	CONSTRAINT FK_ID_USUARIO_DOADOR FOREIGN KEY (ID) REFERENCES USUARIO (ID)
);

CREATE TABLE RECEBIMENTOS(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_DOADOR INT NOT NULL,
    ID_GESTOR INT NOT NULL,
	DATA_RECEBIMENTO DATE NOT NULL,
	VALOR DOUBLE NOT NULL,
	CONSTRAINT FK_DOADOR FOREIGN KEY (ID_DOADOR) REFERENCES DOADOR (ID),
    CONSTRAINT FK_GESTOR FOREIGN KEY (ID_GESTOR) REFERENCES GESTOR (ID)
);

CREATE TABLE MORADOR(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR (50) NOT NULL,
	CPF VARCHAR(11) UNIQUE NOT NULL,
	TELEFONE VARCHAR(20),
	DATA_CADASTRO DATE NOT NULL,
	DATA_NASC DATE NOT NULL,
	STATUS VARCHAR(15),
	ID_IMOVEL INT,
	CONSTRAINT FK_IMOVEL_MORADOR FOREIGN KEY (ID_IMOVEL) REFERENCES IMOVEL (ID)
);

CREATE TABLE CONTRATO_ALUGUEL (
	ID_MORADOR INT NOT NULL,
	ID_IMOVEL INT NOT NULL,
	VALOR_ALUGUEL DOUBLE NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_TERMINO DATE NOT NULL,
	CONSTRAINT FK_MORADOR_CONTRATO FOREIGN KEY (ID_MORADOR) REFERENCES MORADOR (ID),
	CONSTRAINT FK_IMOVEL_CONTRATO FOREIGN KEY (ID_IMOVEL) REFERENCES IMOVEL (ID)
);

CREATE TABLE PARCEIRO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL,
	TIPO VARCHAR (15),
	CNPJ VARCHAR (14) NOT NULL,
	AREA_ATUACAO VARCHAR (15),
	TELEFONE VARCHAR (11),
	CEP VARCHAR (11),
	NUMERO INT
);

CREATE TABLE GASTOS(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_MORADOR INT NOT NULL,
	DATA_GASTO DATE NOT NULL,
	VALOR DOUBLE NOT NULL,
	CONSTRAINT FK_MORADOR_GASTO FOREIGN KEY (ID_MORADOR) REFERENCES MORADOR (ID)
);